Repository aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE, pull requests merged in 2022-10, with the labels that each got.

#399 Update codeql version
  .github/workflows/codeql-analysis.yml
Labels: bug, hacktoberfest-accepted

#398 Add flake8
  .github/workflows/python-package.yml
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  udemy_enroller/__init__.py
  udemy_enroller/cli.py
  udemy_enroller/driver_manager.py
  udemy_enroller/exceptions.py
  udemy_enroller/http.py
  udemy_enroller/logging.py
  udemy_enroller/runner.py
  udemy_enroller/scrapers/__init__.py
  udemy_enroller/scrapers/base_scraper.py
  udemy_enroller/scrapers/coursevania.py
  udemy_enroller/scrapers/discudemy.py
  udemy_enroller/scrapers/freebiesglobal.py
  udemy_enroller/scrapers/manager.py
  udemy_enroller/scrapers/tutorialbar.py
  udemy_enroller/settings.py
  udemy_enroller/udemy_rest.py
  udemy_enroller/udemy_ui.py
  udemy_enroller/utils.py
Labels: low priority issue, hacktoberfest-accepted

#397 Log package and os details on debug
  udemy_enroller/cli.py
Labels: enhancement, hacktoberfest-accepted

#395 Coding improvements
  .github/workflows/python-package.yml
  README.md
  pyproject.toml
  pytest.ini
  run_enroller.py
  setup.cfg
  udemy_enroller/__init__.py
  udemy_enroller/cli.py
  udemy_enroller/driver_manager.py
  udemy_enroller/http_utils.py
  udemy_enroller/logger.py
  udemy_enroller/runner.py
  udemy_enroller/scrapers/coursevania.py
  udemy_enroller/scrapers/discudemy.py
  udemy_enroller/scrapers/freebiesglobal.py
  udemy_enroller/scrapers/tutorialbar.py
  udemy_enroller/settings.py
  udemy_enroller/udemy_rest.py
  udemy_enroller/udemy_ui.py
Labels: low priority issue, hacktoberfest-accepted

#400 Updates to README
  README.md
Labels: documentation, hacktoberfest-accepted

#401 build: add .dockerignore and Dockerfile
  .dockerignore
  Dockerfile
  README.md
Labels: enhancement, hacktoberfest-accepted

#402 Add idownloadcoupon scraper
  README.md
  udemy_enroller/cli.py
  udemy_enroller/runner.py
  udemy_enroller/scrapers/base_scraper.py
  udemy_enroller/scrapers/idownloadcoupon.py
  udemy_enroller/scrapers/manager.py
Labels: enhancement, hacktoberfest-accepted

#403 Add isort profile to pyproject.toml
  pyproject.toml
Labels: good first issue, hacktoberfest-accepted
